package org.vaadin.declarative;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/**
 * !! DO NOT EDIT THIS FILE !!
 *
 * This class is generated by Vaadin Designer and will be overwritten.
 *
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class StorefrontViewDesign extends VerticalLayout {
    protected com.vaadin.ui.Panel searchPanel;
    protected com.vaadin.ui.TextField searchField;
    protected com.vaadin.ui.Button searchButton;
    protected com.vaadin.ui.CheckBox includePast;
    protected com.vaadin.ui.Button newOrder;

    public StorefrontViewDesign() {
        Design.read(this);
    }
}
